### ISSUE TITLE
Installation failed on my YunoHost machine

### ISSUE THREAD

**Issue by drmoeller** [YunoHost-Apps/fittrackee_ynh#12]
### Describe the bug

*Installation fails on my YunoHost machine*

### Context

- Hardware: *Raspberry Pi*
- YunoHost version: 11.1.18
- I have access to my server: *Through SSH as well as through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *as far as I can see: no*
- Using, or trying to install package version/branch: *Current from webadmin interface*

### Steps to reproduce

- *First attempt was to install via webadmin*
- *Second attempt via CLI*
    ```sh
    sudo yunohost app install fittrackee
    ```
- *You will find logs of this attempt pasted on the second YunoPaste URL.*

### Expected behavior

*Successful install*

### Logs

*Please have a look at YunoPaste:*
- 1st attempt via webadmin: https://paste.yunohost.org/raw/paxonopacu
- 2nd attempt via CLI: https://paste.yunohost.org/raw/matajaluni

**Comment by Thovi98** [comment]
Thanks for your issue!
Could you please try again with the new branch and with cli : 
`sudo yunohost app install https://github.com/YunoHost-Apps/fittrackee_ynh/tree/resolve-issue --debug`

**Comment by Thovi98** [comment]
Thanks for your feedback.
Glad it works! Enjoy FitTrackee 🚴‍♀️

**Comment by drmoeller** [comment]
... but now registration of a user succeeds, but login by applying previously created account data **not**.

**Comment by Thovi98** [comment]
Are you talking about the user chosen during the installation or new one (created after installation)?

**Comment by Thovi98** [comment]
There are two options here:
- log in with the one you created during the installation (you had to choose an admin user and password). Then you can activate your other users in the admin section.
- go to [cli](https://github.com/YunoHost-Apps/fittrackee_ynh/blob/master/doc/ADMIN.md) and activate your user. 

You cannot login without first activating your user.

**Comment by drmoeller** [comment]
Ah, OK, tried to click User icon in the upper part of admin page, but didn't tried the "User" at the lower end of the page :-)

**Comment by Thovi98** [comment]
What do you mean? I don’t understand: is your issue resolved?

**Comment by drmoeller** [comment]
Sorry, forgot to answer your question: After application of your hint, login of registered user works as expected. :-)
Thanks.
