### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by kazukyakayashi** [YunoHost-Apps/fittrackee_ynh#15]
### Describe the bug

When I enter the information to connect and I do "Connect", it connects but disconnects automatically right after.
I tried to create another account from the CLI but the problem remains the same.

### Context

- Hardware: Kimsufi KS-1 - Intel ATOM N2800 - 4GB DDR3 
- YunoHost 11.1.18 (stable)
- I have access to my server: SSH

### Logs

```
cat /var/log/fittrackee/fittrackee.log
2023/04/20 12:35:17 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
2023/04/20 12:35:18 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
```

**Comment by Thovi98** [comment]
Or update to the new version of the package (it will be available in a few hours in the webadmin, issue must be then resolved!
