### ISSUE TITLE
Installation failling

### ISSUE THREAD

**Issue by ernesst** [YunoHost-Apps/fittrackee_ynh#22]
### Describe the bug

Hello, 
I cannot go to the end of the installation, it's crashing on the virtualenv creation.

### Context

- Hardware: ROCK64, arm64 board, std debian 11 install + curl the yunohost script.
- YunoHost version: 11.1.20
- I have access to my server: *Through SSH yunohost app install https://github.com/YunoHost-Apps/fittrackee_ynh/tree/testing --debug
| through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
yunohost app install https://github.com/YunoHost-Apps/fittrackee_ynh/tree/testing --debug

### Expected behavior

Please see :  https://paste.yunohost.org/raw/axocahaxir

### Logs

Thanks for the app, looks interesting.

**Comment by Thovi98** [comment]
Thanks for your issue!
I think it’s because some remainings in virtualenv

Could you please try via ssh `apt remove python3-virtualenv` and then try the install again?

**Comment by ernesst** [comment]
Seems a compatibility issue with ffsync yunohost package.
 ```
~# apt remove python3-virtualenv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  pypy pypy-dev pypy-lib python3-distlib python3-filelock
  python3-importlib-metadata python3-more-itertools python3-zipp
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ffsync-ynh-deps python3-virtualenv

```

After removing it I can get fittrackee working.
