### ISSUE TITLE
Failed to Upload .gpx files

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/fittrackee_ynh#26]
### Describe the bug

I can not upload .gpx files

### Context

- Hardware:  raspi 4b
- YunoHost version: 11.1.22 (stable)
- I have access to my server: yes, both
- Using, or trying to install package version/branch: fittrackee 0.7.18 (latest)

### Steps to reproduce

trying to **add workout** using .gpx file Fittrackee fails.

Two errors:

- visualcrossing API was deleted after latest upgrade (It was set)  - **SOLVED** adding API again.
-  module PIL.image has no Antialias attribute

### Expected behavior

proccess .gpx without issues

### Logs

```
2023/07/14 05:43:05 - fittrackee - ERROR - error when getting weather data: 401 Client Error:  for url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/41.xxxxx,-3.xxxxxx/sssssssssss?key=False&iconSet=icons1&unitGroup=metric&contentType=json&elements=datetime%2CdatetimeEpoch%2Ctemp%2Chumidity%2Cwindspeed%2Cwinddir%2Cconditions%2Cdescription%2Cicon&include=current
2023/07/14 05:43:05 - fittrackee - ERROR - module 'PIL.Image' has no attribute 'ANTIALIAS'
2023/07/14 05:48:28 - dramatiq.WorkerProcess(0) - WARNING - Killing worker process...
2023/07/14 05:48:28 - dramatiq.WorkerProcess(1) - WARNING - Killing worker process...
2023/07/14 05:48:28 - dramatiq.ForkProcess(0) - WARNING - Killing fork process...
2023/07/14 05:48:31 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
2023/07/14 05:48:33 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
2023/07/14 05:48:55 - fittrackee - ERROR - module 'PIL.Image' has no attribute 'ANTIALIAS'
2023/07/14 05:50:02 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
2023/07/14 05:50:20 - dramatiq.WorkerProcess(0) - WARNING - Killing worker process...
2023/07/14 05:50:20 - dramatiq.WorkerProcess(1) - WARNING - Killing worker process...
2023/07/14 05:50:24 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
2023/07/14 05:50:56 - fittrackee - ERROR - module 'PIL.Image' has no attribute 'ANTIALIAS'
```

- first ERROR is **solved* after adding API key again (at least there's not in the logs)

- could email _warning_ being an issue? 

- is module problem from upstream? I have not found any _issue_ in their repo

look at _log_ timestamp, I paste here three consecutive diferent attempts

thank you

**Comment by Thovi98** [comment]
Thanks for letting me know!
Could you please try install/upgrade with the following branch? https://github.com/YunoHost-Apps/fittrackee_ynh

Thanks

**Comment by xmgz** [comment]
do you mean the **testing branch**?

sudo yunohost app upgrade fittrackee -u https://github.com/YunoHost-Apps/fittrackee_ynh/tree/testing --debug

**Comment by Thovi98** [comment]
Oops sorry, went to fast. Yes, testing branch is fine!

**Comment by xmgz** [comment]
I could upload some files after upgrading to test branch. Thank you.


Please, will I have to manually upgrade to "stable" branch when you publish 0.7.19 or will it automatically notify about the new version? Thank you.

**Comment by Thovi98** [comment]
Sorry for the late reply!
You will not have to do anything manually. There will soon be the 0.7.21 upgrade and you will be notified in the webadmin.
