### ISSUE TITLE
Ajout d'utilisateur inactifs par défaut

### ISSUE THREAD

**Issue by microniko** [YunoHost-Apps/fittrackee_ynh#29]
Lorsqu'un nouvel utilisateur se créé un compte sur FitTrackee, par défaut il est **inactif**. De plus, comme l'envoi des courriels est désactivé avec l'installation dans Ynh, aucun administrateur n'est informé qu'il faut activer cet utilisateur.

Le nouvel utilisateur ne sait pas non plus que son compte doit être activé avant de pouvoir se connecter.
 
- FitTrackee v0.7.21
- YunoHost version: 11.2.3

Dans la Doc de FitTrackee : 

> Après l’enregistrement, le compte d’utilisateur est inactif et un courriel contenant des instructions de confirmation est envoyé pour l’activer.

Suggestions :
- Rendre actif les nouveaux utilisateurs par défaut. Inconvénient : risque important de spam.
- Activer l'envoi de courriels par FitTrackee pour que le processus d'activation du compte puisse se faire correctement.

Question annexe : qu'est-ce qu'il manque à FitTrackee pour que la gestion des utilisateurs soit portée par Yunohost ?

**Comment by Thovi98** [comment]
Merci d’avoir lancé cette discussion.
En effet, l’envoi des courriels est désactivé par défaut. C’était une contrainte de Yunohost jusqu’à la version 11.2.0.
Maintenant, il m’est possible de l’activer, mais je butte encore sur des erreurs.

En attendant, il est possible d’activer le compte d’un utilisateur grâce à l’administrateur ou par ligne de commande.
Je ne suis pas certain qu’on puisse rendre actif les nouveaux utilisateurs par défaut. Mais je pense que c’est une mauvaise idée dans tous les cas, vu qu’on peut les activer manuellement.

**Comment by microniko** [comment]
Merci de travailler là-dessus.
Je vais attendre patiemment ;-)

Je n'ai pas trouvé la doc pour utiliser le SSO de Yunohost pour évaluer la hauteur de la marche.
Visiblement, la [question a été ± soulevée](https://github.com/SamR1/FitTrackee/issues/312) du côté de FitTrackee ;-)
