### ISSUE TITLE
Perte de la clé API lors d'une mise à jour

### ISSUE THREAD

**Issue by microniko** [YunoHost-Apps/fittrackee_ynh#44]
Lors d'une mise à jour, la clé api pour la météo est perdue. Il faut la renseigner à nouveau dans le formulaire de configuration du panel Yunohost.

Testé de *0.7.22~ynh1* vers *0.7.25~ynh1* et de *0.7.25~ynh1* vers la version en test.

**Comment by Thovi98** [comment]
Tiens, je n’ai jamais eu ce problème 🤔
Tu sais me donner les logs de ta dernière mise à jour ?

**Comment by microniko** [comment]
Je n'aime pas trop laisser les logs complets sur Github. 
Peux-tu supprimer le message une fois lu : https://paste.yunohost.org/eponimozif.sql
(j'ai retirer la variable `WEATHER_API_KEY` du log).

**Comment by Thovi98** [comment]
Merci ! J'essaie d'analyser ça rapidement :)

**Comment by Thovi98** [comment]
Petite intuition : est-ce que tu as ajouté l'api météo lors de l'installation ou seulement par la suite via le config_panel ?

**Comment by microniko** [comment]
Oh là là… Je crois que j'ai ajouté la config après.

**Comment by Thovi98** [comment]
Okay bien !
C'est donc la raison pourquoi ça fonctionne pour moi mais pas pour toi.

J'ai une idée pour réparer ça, je te demanderai de tester quand ce sera fait, si ça ne te dérange pas :)

**Comment by Thovi98** [comment]
J’ai fait un fix je pense dans la version testing (qui sera bientôt fusionnée en master).
N’hésite pas à me faire savoir si ça a fonctionné ou pas (copie peut-être ta clé avant de faire la mise à jour comme ça tu ne dois pas la rechercher sur le site, au cas où) 🙈

**Comment by Thovi98** [comment]
Je serais intéressé de savoir si ça aura fonctionné :D

**Comment by microniko** [comment]
Désolé. Je viens de mettre à jour vers 0.7.26~ynh1 et il a perdu la clé (`FALSE` dans le champ) :-(

**Comment by Thovi98** [comment]
Merci pour le test, je vais continuer mes investigations 😇

**Comment by microniko** [comment]
Mise à jour vers 0.7.27~ynh1 faite !
La clé API a bien été perdue, je te confirme qu'elle est bien conservée à la prochaine mise à jour.

**Comment by microniko** [comment]
Je viens de mettre à jour vers 0.7.28~ynh1, la clé API a bien été conservée !
Merci !

**Comment by Thovi98** [comment]
Merci pour ton retour et ta patience ! 🎉
