### ISSUE TITLE
admin and password

### ISSUE THREAD

**Issue by chri2** [YunoHost-Apps/fittrackee_ynh#66]
During installation an admin is chosen from the yunohost database by its uid only. Furthermore a password is given.

After install the login for the app asks for credentials and denies login by the chosen credentials, because it expects an email address.

I needed some guessing on my system (several domains configured) to guess that the admin username is <chosen user>@<main domain>.

This could be better communicated.

**Comment by Thovi98** [comment]
Could you please confirm that https://github.com/YunoHost-Apps/fittrackee_ynh/pull/69 solves what you meant for this issue?

**Comment by chri2** [comment]
👍
