### ISSUE TITLE
Is this package compatible with YunoHost 12.0 (Bookworm) release ?

### ISSUE THREAD

**Issue by microniko** [YunoHost-Apps/fittrackee_ynh#88]
All is in the title ;-)

**Comment by Thovi98** [comment]
Yes, it _should_ work ^^

On my end, I’m on Yunohost 12 for several months and FitTrackee works without issue.

Feel free to try and report back :)

**Comment by microniko** [comment]
Yes. I did updating Yunohost to 12 and FitTrakee works :-)
